name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and save results
        run: npm test | tee test-results.txt
        continue-on-error: true

      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./test-results

      - name: Display test results
        run: cat ./test-results/test-results.txt

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start
