deploy:
  needs: test
  runs-on: self-hosted

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set PowerShell Execution Policy
      run: PowerShell -Command "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force"

    - name: Fix Permissions
      run: chmod -R 755 ./src

    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./test-results

    - name: Show test results
      run: cat ./test-results/test-results.txt

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: pm2 delete node-app || true && pm2 start "./src/server.js" --name node-app && pm2 save
