name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and save results
        run: |
          npm test | tee test-results.txt
        continue-on-error: true

      - name: Ensure test results file exists
        run: |
          if [ ! -f test-results.txt ]; then
            echo "No test results found. Creating an empty file."
            touch test-results.txt
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt